"""empty message

Revision ID: 49e22743d690
Revises: dc4d21bd9996
Create Date: 2021-03-15 11:51:31.852933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e22743d690'
down_revision = 'dc4d21bd9996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
